#!/usr/bin/env zsh
# Test script for GoblinOS Desktop new features
# Run this after starting the dev server with: npm run dev

set -e

echo "==================================================="
echo "GoblinOS Desktop - Feature Test Script"
echo "==================================================="
echo ""

echo "Prerequisites:"
echo "1. Dev server must be running: cd desktop && npm run dev"
echo "2. Ollama must be running: ollama serve"
echo "3. A model must be pulled: ollama pull qwen2.5:3b"
echo ""
echo "Press Enter to continue or Ctrl+C to cancel..."
read

echo ""
echo "Test 1: Verify providers (should include 'ollama')"
echo "---------------------------------------------------"
echo "Open Tauri devtools and run:"
echo ""
echo "  await __TAURI__.invoke('get_providers')"
echo ""
echo "Expected output: [\"ollama\"]"
echo "(If you set API keys, you'll see 'openai', 'anthropic', 'gemini')"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Test 2: Execute non-streaming task"
echo "---------------------------------------------------"
echo "In Tauri devtools, run:"
echo ""
echo "  const response = await __TAURI__.invoke('execute_task', {"
echo "    request: { goblin: 'codesmith', task: 'Say hello', streaming: false }"
echo "  });"
echo "  console.log(response.reasoning);"
echo "  console.log('Duration:', response.duration_ms, 'ms');"
echo "  console.log('Model:', response.model);"
echo "  console.log('Cost:', response.cost);"
echo ""
echo "Expected: Text response from Ollama, cost should be null (free)"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Test 3: Execute streaming task"
echo "---------------------------------------------------"
echo "In Tauri devtools, run:"
echo ""
echo "  // Set up listener FIRST"
echo "  await window.__TAURI__.event.listen('stream-token', (event) => {"
echo "    console.log('Token:', event.payload.content);"
echo "    if (event.payload.done) console.log('✅ Done!');"
echo "  });"
echo ""
echo "  // Then execute with streaming"
echo "  await __TAURI__.invoke('execute_task', {"
echo "    request: { goblin: 'codesmith', task: 'Count to 5', streaming: true }"
echo "  });"
echo ""
echo "Expected: Tokens appear progressively in console"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Test 4: Parse orchestration"
echo "---------------------------------------------------"
echo "In Tauri devtools, run:"
echo ""
echo "  const plan = await __TAURI__.invoke('parse_orchestration', {"
echo "    text: 'build THEN test AND lint',"
echo "    defaultGoblin: 'codesmith'"
echo "  });"
echo "  console.log('Total steps:', plan.metadata.total_steps);"
echo "  console.log('Parallel batches:', plan.metadata.parallel_batches);"
echo "  plan.steps.forEach(step => {"
echo "    console.log(\`\${step.id}: \${step.task} (deps: \${step.dependencies})\`);"
echo "  });"
echo ""
echo "Expected: Plan with 3 steps, 2 parallel batches"
echo "Step 1: 'build' (no deps)"
echo "Step 2: 'test' (depends on step 1)"
echo "Step 3: 'lint' (depends on step 1)"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Test 5: Get cost summary"
echo "---------------------------------------------------"
echo "In Tauri devtools, run:"
echo ""
echo "  const summary = await __TAURI__.invoke('get_cost_summary');"
echo "  console.log('Total tasks:', summary.total_tasks);"
echo "  console.log('Total cost:', summary.total_cost);"
echo "  console.log('Cost by provider:', summary.cost_by_provider);"
echo ""
echo "Expected: Total cost should be 0.0 for Ollama (free)"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "Test 6: Advanced orchestration with conditionals"
echo "---------------------------------------------------"
echo "In Tauri devtools, run:"
echo ""
echo "  const plan = await __TAURI__.invoke('parse_orchestration', {"
echo "    text: 'build THEN test IF_SUCCESS THEN deploy',"
echo "    defaultGoblin: 'codesmith'"
echo "  });"
echo "  console.log(plan.steps.map(s => ({"
echo "    task: s.task,"
echo "    condition: s.condition"
echo "  })));"
echo ""
echo "Expected: Step 2 (test) has IF_SUCCESS condition on step 1"
echo ""
echo "Press Enter to continue..."
read

echo ""
echo "==================================================="
echo "✅ All test instructions provided!"
echo "==================================================="
echo ""
echo "Environment variables for cloud providers (optional):"
echo "  export OPENAI_API_KEY=sk-..."
echo "  export ANTHROPIC_API_KEY=sk-ant-..."
echo "  export GEMINI_API_KEY=AIza..."
echo ""
echo "Then restart dev server to see those providers."
echo ""
echo "For detailed info, see: INTEGRATION_SUMMARY.md"
