from __future__ import annotations

from fastapi import FastAPI

from ..route_mounting import (
    mount_primary_routes,
    mount_versioned_primary_routes,
)


def register_routes(
    app: FastAPI,
    *,
    api_router,
    auth_router,
    routing_router,
    parse_router,
    raptor_router,
    api_keys_router,
    settings_router,
    search_router,
    stream_router,
    chat_router,
    semantic_chat_router,
    write_time_router,
    health_router,
    ops_router,
    secrets_router,
    privacy_router,
    model_suggestion_debug_router,
    observability_debug_router,
    sandbox_router,
    providers_models_router,
    account_router,
    support_router,
    routing_analytics_available: bool,
    routing_analytics_router,
) -> None:
    mount_primary_routes(
        app,
        api_router=api_router,
        auth_router=auth_router,
        routing_router=routing_router,
        parse_router=parse_router,
        raptor_router=raptor_router,
        api_keys_router=api_keys_router,
        settings_router=settings_router,
        search_router=search_router,
        stream_router=stream_router,
        chat_router=chat_router,
        semantic_chat_router=semantic_chat_router,
        write_time_router=write_time_router,
        health_router=health_router,
        ops_router=ops_router,
        secrets_router=secrets_router,
        privacy_router=privacy_router,
        model_suggestion_debug_router=model_suggestion_debug_router,
        observability_debug_router=observability_debug_router,
        sandbox_router=sandbox_router,
        providers_models_router=providers_models_router,
        account_router=account_router,
        support_router=support_router,
        routing_analytics_available=routing_analytics_available,
        routing_analytics_router=routing_analytics_router,
    )

    mount_versioned_primary_routes(
        app,
        health_router=health_router,
        settings_router=settings_router,
        providers_models_router=providers_models_router,
        chat_router=chat_router,
        api_router=api_router,
        auth_router=auth_router,
        search_router=search_router,
        sandbox_router=sandbox_router,
        account_router=account_router,
        support_router=support_router,
        raptor_router=raptor_router,
        api_keys_router=api_keys_router,
        privacy_router=privacy_router,
        routing_router=routing_router,
        parse_router=parse_router,
        write_time_router=write_time_router,
        stream_router=stream_router,
        ops_router=ops_router,
        secrets_router=secrets_router,
    )
