# Datadog Agent Configuration for Goblin Assistant
# Store API key and app key in environment variables or vault
# DATADOG_API_KEY=your-api-key-here
# DATADOG_APP_KEY=your-app-key-here (for API access)

api_key: ${DATADOG_API_KEY}
app_key: ${DATADOG_APP_KEY}

env: ${DD_ENV:dev}
service: goblin-assistant

tags:
  - env:${DD_ENV:dev}
  - service:goblin-assistant
  - team:goblinos
  - project:goblin-assistant

logs_enabled: true

logs_config:
  use_http: true
  use_compression: true
  compression_level: 6
  batch_wait: 5
  open_files_limit: 500

apm_config:
  enabled: true
  env: ${DD_ENV:dev}
  service_name: goblin-assistant-api
  receiver_port: 8126
  max_traces_per_second: 100
  max_memory: 1000000000
  max_cpu_percent: 50

statsd_port: 8125
statsd_forward_host: ""
statsd_forward_port: 0
statsd_metric_namespace: goblin

process_config:
  enabled: true
  intervals:
    process: 10

system_probe_config:
  enabled: false

container_collect_all: true

confd_path: /opt/datadog-agent/etc/conf.d

logs:
  - type: file
    path: /var/log/goblin-assistant/*.log
    service: goblin-assistant
    source: python
    sourcecategory: sourcecode
  - type: docker
    image: goblin-assistant
    service: goblin-assistant
    source: docker
